### ISSUE TITLE
Data.xml isn't included in the solution

### ISSUE THREAD

**Issue by Wycott** [Fuinny/Oligopoly#1]
Data.xml isn't included in the solution and so isn't deployed when the project is built. This means the game doesn't function correctly unless this file is copied to:

...\Oligopoly\Oligopoly\bin\Debug\net7.0

**Comment by Fuinny** [comment]
> Data.xml isn't included in the solution and so isn't deployed when the project is built. This means the game doesn't function correctly unless this file is copied to:
> 
> ...\Oligopoly\Oligopoly\bin\Debug\net7.0

Thank you! I added the file to the solution and posted the modified version. Now everything should work well. Thanks again!
