### ISSUE TITLE
Add menu to the game

### ISSUE THREAD

**Issue by hunterlan** [Fuinny/Oligopoly#3]
Hi! I liked your idea of a game and now it looks good. I'd like to see a menu (pause) for the game, where I can load/save game and exit from it.

**Comment by Fuinny** [comment]
Hello! Thank you for paying attention to my game and for suggesting improvements to it! I like the idea of saves and the pause menu. I'll try to implement something similar, but I'm sure it will take me some time because I'm not sure how to do it yet. Thanks anyway! :D
